apiVersion: v1
kind: Service
metadata:
  name: mysql-deploy
  labels:
    app: mysql-deploy
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.mysql.service.port }}
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql-deploy
