apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  mysql-database: wordpress
  mysql-password: "<your-mysql-password>"
  mysql-root-password: "<your-mysql-root-password>"
  mysql-user: wpuser

